return {
	ensure_installed = {
		"debugpy",
		"delve",
		"dockerfile-language-server",
		--[[ "eslint-lsp", ]]
		"eslint_d",
		"gofumpt",
		"golines",
		"gotests",
		"impl",
		"json-to-struct",
		"kotlin-language-server",
		"lua-language-server",
		"luacheck",
		"pyright",
		"rust-analyzer",
		"shellcheck",
		"shfmt",
		"solidity",
		"staticcheck",
	},
	auto_update = true,
	run_on_start = false,
}
