#!/bin/sh

/usr/bin/pgrep -x sxhkd > /dev/null || sxhkd &

# Workspaces
bspc monitor -d 1 2 3 4 5 6 7 8 9 web

# Windows Config
bspc config border_width 0
bspc config focus_follows_pointer true
bspc config pointer_modifier mod1
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Mice bindings
#   Alt + Left Click to move floating windows
bspc config pointer_action1 move

#   Alt + Right Click resizes the window by side
bspc config pointer_action3 resize_side

#   Alt + Right Click button resize by corner
bspc config pointer_action3 resize_corner

bspc rule -a Chromium desktop='web'
bspc rule -a "Vivaldi-stable" desktop='web'
bspc rule -a "*":"Popup" state=floating
bspc rule -a "feh" state=floating
bspc rule -a "mpv" state=floating

