[tools]
actionlint = "latest"
atlas = "latest"
aws = { version = "latest", symlink_bins = "true" }
btop = "1.4.5"
bun = "latest"
codex = "latest"
fzf = "latest"
gdu = "latest"
github-cli = "latest"
go = "1"
"go:github.com/sqlc-dev/sqlc/cmd/sqlc" = "latest"
golangci-lint = "latest"
gradle = "latest"
java = "corretto-17"
maven = "latest"
node = "24"
postgres = "17"
pre-commit = "latest"
pulumi = "latest"
python = "latest"
rclone = "latest"
ripgrep = "latest"
usage = "latest"
uv = "latest"
act = "latest"
lazygit = "latest"
"pipx:visidata" = "latest"
ffmpeg = "latest"
chezmoi = "latest"
amazon-ecr-credential-helper = "latest"
starship = "latest"
eza = "latest"
"go:github.com/jesseduffield/lazygit" = "latest"
neovim = "latest"
"go:github.com/go-delve/delve/cmd/dlv" = "master"
rust = "latest"
bitwarden = "latest"
